### ISSUE TITLE
Error generating plugin

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/sfdx-plugin-generate#23]
I've been using the plugin generator without any issues up until now, but today I received the following error when creating the plugin (and also if I executed "yarn run prepare") : 

--- snip ---

$ rm -rf lib && tsc && oclif-dev manifest && oclif-dev readme
src/commands/hello/org.ts(11,22): error TS2417: Class static side 'typeof Org' incorrectly extends base class static side 'typeof SfdxCommand'.
  Types of property 'flagsConfig' are incompatible.
    Type '{ name: IOptionFlag<string>; force: IBooleanFlag<boolean>; }' is not assignable to type 'SfdxFlagsConfig'.
      Property 'name' is incompatible with index signature.
        Type 'IOptionFlag<string>' is not assignable to type 'string | boolean | IBooleanFlag<any> | JsonMap | IOptionFlag<any>'.
          Type 'IOptionFlag<string>' is not assignable to type 'IOptionFlag<any>'.
            Type 'IOptionFlag<string>' is not assignable to type '{ completion?: ICompletion; }'.
              Types of property 'completion' are incompatible.
                Type 'ICompletion' is not assignable to type 'ICompletion'. Two different types with this name exist, but they are unrelated.
                  Types of property 'cacheKey' are incompatible.
                    Type '(ctx: ICompletionContext) => Promise<string>' is not assignable to type '(ctx: ICompletionContext) => Promise<string>'. Two different types with this name exist, but they are unrelated.
                      Types of parameters 'ctx' and 'ctx' are incompatible.
                        Type 'ICompletionContext' is not assignable to type 'ICompletionContext'. Two different types with this name exist, but they are unrelated.
                          Types of property 'config' are incompatible.
                            Type 'IConfig' is not assignable to type 'IConfig'. Two different types with this name exist, but they are unrelated.
                              Property 'channel' is missing in type 'IConfig'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

--- snip ---

I've added the full output in the attachment - 
[plugin_generate_output.txt](https://github.com/forcedotcom/sfdx-plugin-generate/files/2053752/plugin_generate_output.txt)

System info:

ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202

sfdx version:

sfdx-cli/6.17.0-b1f53723b9 (darwin-x64) node-v8.9.4

In case it was anything specific to my name/description etc, I've also tried creating one where I accept the defaults for everything other than the name, but got the same result.

**Comment by dcarroll** [comment]
One difference I see in my output versus yours based on a rudimentary scan is that your Yarn version is behind mine.  I've got yarn v1.3.2 where you are showing yarn v1.2.1.

My generate fails in spite of the difference.  Looking for other reasons....

**Comment by amphro** [comment]
Dup of #22
