### ISSUE TITLE
Plugin failure after install of sfdx for windows

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/sfdx-plugin-generate#25]
Hi ,

It seems automatic scripts to load dependencies of SFDX plugins contains hardcoded Linux instructions.

Would it be possible to check the current system, or use cross-platform languages to perform file operations ?

To reproduce:

- Install plugin sfdx_metadatas_filtering 
`sfdx plugins:install sfdx_metadatas_filtering`

- Launch a standard command like `sfdx force:org:open` -> the plugin dependencies retrieval will be initiated, then it will crash when "rm" command is triggered

Many thanks & best regards 

![image](https://user-images.githubusercontent.com/17500430/40850322-a54b9628-65c4-11e8-995a-31e2c844bd2c.png)

**Comment by amphro** [comment]
This should have been resolved with #27
