### ISSUE TITLE
--dev-suspend not working

### ISSUE THREAD

**Issue by venkatpolisetti** [forcedotcom/sfdx-plugin-generate#33]
I am getting an error while trying to run my plugin with --dev-suspend flag.

$ sfdx test:myplugin:set -u xxx -d ./fields.csv --dev-suspend
ERROR running set:  Unexpected argument: --dev-suspend
See more help with --help

OS:Windows 7, using bash shell
$ sfdx --version
sfdx-cli/6.34.0-6fec0d751a (windows-x64) node-v8.9.4

**Comment by amphro** [comment]
Unfortunately --dev-suspend is not supported on windows right now. You can use the environment variable `NODE_OPTIONS=--inspect-brk`. We will update the docs.

**Comment by venkatpolisetti** [comment]
Thank you for your quick reply.

That is what I ended up using, but it would have been easy to use --dev-suspend with the actual plugin rather using ./bin/run with NODE_OPTIONS.

Hopefully, it would make it to windows soon.
