### ISSUE TITLE
sfdx plugins:install @<org_scope>/<plugin_name> error: pluginName cannot be nll

### ISSUE THREAD

**Issue by squibobblepants** [forcedotcom/sfdx-plugin-generate#4]
I thought I'd try my hand at writing a plugin for the sfdx cli, which I succeeded at. I was able to publish it publically to npm as my user ([https://www.npmjs.com/package/dsy-sfdx-plugins](https://www.npmjs.com/package/dsy-sfdx-plugins)), and install it in the cli using 
`sfdx plugins:install dsy-sfdx-plugins`

However I then realised I would prefer it to be listed under my Company's Organization, so I created one, changed the scope of the package to my new Organization, and published it like so (forcing it to be public):
`npm publish --access public`
This appeared on npm correctly: [https://www.npmjs.com/package/@desynit/dsy-sfdx-plugins](https://www.npmjs.com/package/@desynit/dsy-sfdx-plugins) and marked as public. Hooray!

BUT THEN
When I tried to install it I saw the following error:
`
$ sfdx plugins:install @desynit/dsy-sfdx-plugins
Installing plugin @desynit/dsy-sfdx-plugins...
Installing plugin @desynit/dsy-sfdx-plugins... Checking for digital signature.
 !    pluginName cannot be nll
`
![pluginname cannot be nll](https://user-images.githubusercontent.com/866931/38690689-a2599a20-3e76-11e8-9b28-5d90c309042c.png)

I assume this is an issue with the sfdx plugin machinery somewhere, and I think this is the best place to enquire about it / report the issue?

**Comment by tnoonan-salesforce** [comment]
@squibobblepants Thanks for opening the issue. We are aware of this problem and I'm actually working on a fix for this as I type this. As you surmised, the digital signature check doesn't support scopes in the npm names.

**Comment by amphro** [comment]
This should be fixed now with the latest version of the cli `sfdx-cli/6.13.0`.

**Comment by squibobblepants** [comment]
I'm afraid this doesn't work for me on version 6.13.0

```
$ sfdx plugins:install @desynit/dsy-sfdx-plugins
Installing plugin @desynit/dsy-sfdx-plugins...
Installing plugin @desynit/dsy-sfdx-plugins... Checking for digital signature.
Finished digital signature check. Skipping... !
 !    The url request returned 404 - https://registry.npmjs.org/@desynit/dsy-sfdx-plugins
```

I think the problem is that the forward slash needs to be html encoded like so:
`https://registry.npmjs.org/@desynit%2fdsy-sfdx-plugins`

But If I do that in the cli like so
```
$ sfdx plugins:install @desynit%2fdsy-sfdx-plugins
Installing plugin @desynit%2fdsy-sfdx-plugins...
Installing plugin @desynit%2fdsy-sfdx-plugins... Checking for digital signature.
 !    The npm name is missing or invalid.
```

It doesn't work. Am I missing something maybe?

Version info:
```
$ sfdx --version
sfdx-cli/6.13.0-3bc8bd73d8 (windows-x64) node-v8.9.4
```

**Comment by amphro** [comment]
We actually ran into that problem on one of our local npm servers but not the other OR with registry.npmjs.org. Now when I do it against npmjs, I get the same error... @tnoonan-salesforce I think we will have to add in the encoding after all.
