### ISSUE TITLE
Wrong type definitions fetched for DescribeGlobalResult and DescribeGlobalSObjectResult

### ISSUE THREAD

**Issue by catalandres** [forcedotcom/sfdx-plugin-generate#48]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
* Create a new folder and go into it using `cd`.
* Run `sfdx plugins:generate` and hit enter to run with the default settings.
* Run `more ./node_modules/@types/jsforce/describe-result.d.ts`
* The following content appears:
```
export interface DescribeSObjectResult {
    label: string;
    fields: object[];
}

export interface DescribeGlobalResult {
    activateable: boolean;
    createable: boolean;
    custom: boolean;
    customSetting: boolean;
    deletable: boolean;
    deprecatedAndHidden: boolean;
    feedEnabled: boolean;
    hasSubtypes: boolean;
    isSubtype: boolean;
    keyPrefix: string;
    label: string;
    labelPlural: string;
    layoutable: boolean;
    mergeable: boolean;
    mruEnabled: boolean;
    name: string;
    queryable: boolean;
    replicateable: boolean;
    retrieveable: boolean;
    searchable: boolean;
    triggerable: boolean;
    undeletable: boolean;
    updateable: boolean;
}
```
* This is clearly wrong when compared against [the corresponding official SOAP API documentation](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_describeglobal_describeglobalresult.htm)

What is the expected behavior?
------------------------------
The content should be that of [this file from the TS type definitions for JSForce in DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsforce/describe-result.d.ts).

SFDX version: sfdx-cli/6.43.1-6021deb31d (darwin-x64) node-v8.9.4
OS version: macOS 10.14.2

```
sfdx plugins --core
@salesforce/plugin-generator 1.0.1 (core)
@salesforce/sfdx-trust 1.0.8 (core)
builtins 1.0.0 (core)
salesforcedx 44.10.0 (core)
```

**Comment by rbergman** [comment]
This is not really a bug -- `sfdx-core` has pinned the versions of both `jsforce` and `@types/jsforce` that it relies on, which is resulting in you seeing earlier versions of the `jsforce` typings.  That said, we can probably get these versions updated.  I'll open an internal work item to address it, but feel free to open your own issue against core to track updating both of those packages and we'll close it out when complete.

**Comment by catalandres** [comment]
Thanks, @rbergman. 
It's the first Javascript project that I am trying to contribute to — still finding my way.

**Comment by rbergman** [comment]
No problem!
