### ISSUE TITLE
hello:org example does not work

### ISSUE THREAD

**Issue by trebleCode** [forcedotcom/sfdx-plugin-generate#50]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
*bug*
What is the current behavior?
-----------------------------
From my desktop on a personal machine:
```
sfdx plugins:generate testplug --defaults
cd .\testplug\
.\bin\run sfdx hello:org -h
```

Result:  
`Error: command sfdx not found`

What is the expected behavior?
------------------------------
Command to compile and write to the console the behavior from the example

All below are in system environment variable PATH and user environment variable PATH:

> C:\Users\myusername\AppData\Roaming\nvm
> C:\Program Files\nodejs
> C:\Users\myusername\AppData\Roaming\npm
> C:\Program Files\Salesforce CLI\bin
> C:\Users\myusername\AppData\Local\sfdx\client\bin

Config:

> OS Name:                   Microsoft Windows 10 Pro
> OS Version:                10.0.17134 N/A Build 17134
> Node: v8.11.4
> NPM: 5.6.0
> SFDX: sfdx-cli/6.44.0-dead729fb5 (windows-x64) node-v8.9.4

Attempting to follow example posted @ **https://developer.salesforce.com/docs/atlas.en-us.216.0.sfdx_cli_plugins.meta/sfdx_cli_plugins/cli_plugins_generate_scaffold.htm**

Please let me know any additional steps if needed.

**Comment by rbergman** [comment]
Thanks for the report.  This is a simple error in the docs.  I'll file an issue internally to get it corrected.  The last line of your example should look like this instead:

```
.\bin\run hello:org -h
```

**Comment by rbergman** [comment]
We're now tracking this internally, so I'm closing here.

**Comment by trebleCode** [comment]
Thanks @rbergman
