### ISSUE TITLE
Generated plugin fails when linking

### ISSUE THREAD

**Issue by trebleCode** [forcedotcom/sfdx-plugin-generate#51]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug

What is the current behavior?
-----------------------------
Returns an error message when trying to link a generated plugin

```
mkdir plug1
cd .\plug1
sfdx plugins:generate plug1
```

It generates the expected scaffolding files.
When attempting to install dependencies, it gets to

```
sam
[3/5] Fetching packages...
[.......................................................................................] 0/202The system cannot find the path specified
```

I then run:
`sfdx plugins:link`

and get this output:

```
Installing dependencies for C:\Users\myusername\Desktop\plug1
|     yarn --non-interactive
|     --mutex=file:C:\Users\myusername\AppData\Local\sfdx\yarn
|     --cache-folder=C:\Users\myusernae\AppData\Local\sfdx\yarn exited
|    with code 1
|    error Command failed with exit code 1
|
```

Then try:
`sfdx hello:org -u myPreviouslySetAlias`

I receive:

```
|    hello:org is not a sfdx command
|    Perhaps you meant force:org
|    Run sfdx help for a list of available topics
```

What is the expected behavior?
------------------------------
It should print out the org command from the generated example

OS: 10.0.16299 N/A Build 16299
SFDX CLI Version: sfdx-cli/6.44.0-dead729fb5 (windows-x64) node-v8.9.4
Node: 8.9.4
NPM: 6.4.1

**Comment by amphro** [comment]
This should be fixed with v7. Please reopen if it is not.
