### ISSUE TITLE
Version of Node required is different to developer guide

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/sfdx-plugin-generate#52]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Bug

What is the current behavior?
-----------------------------
1. Prepare computer as per the [docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_plugins.meta/sfdx_cli_plugins/cli_plugins_generate_prepare.htm), including checking that I have version 8 of node - I have 8.4.0 installed.
1. Scaffold plugin as per the [docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_plugins.meta/sfdx_cli_plugins/cli_plugins_generate_scaffold.htm)

Throws the following error:

[3/5] 🚚  Fetching packages...
error sfdx-faye@1.0.9: The engine "node" is incompatible with this module. Expected version ">=8.9.4".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
(node:96523) [MODULE_NOT_FOUND] Error Plugin: mentz: Cannot find module '@salesforce/command'

This resulted in the dependencies stanza of package.json being left empty and the plugin failing to run as it couldn't find the @salesforce/command module.

Using node version 8.9.4, everything worked as expected.

What is the expected behavior?
------------------------------
The version of node detailed in the docs should allow the plugin generator to successfully scaffold the plugin.

Please mention your Salesforce CLI and OS version.

CLi sfdx-cli/6.44.0-dead729fb5 (darwin-x64) node-v8.9.4

OS: Mac OS X	10.14.2	18C54

**Comment by ruthemmanuelle** [comment]
Thanks for the feedback, @keirbowden. We've updated the doc you mentioned to state that the long-term support (LTS) version of Node.js is required. The updated doc should be available later today. In the meantime, you can find the LTS version number here: https://nodejs.org/en/download/
