### ISSUE TITLE
plugin help shows <%= command.id %> instead of hello:org

### ISSUE THREAD

**Issue by jayree** [forcedotcom/sfdx-plugin-generate#55]
### Summary

plugin help shows <%= command.id %> instead of hello:org

### Steps To Reproduce:

1.  sfdx plugins:generate
1.  sfdx plugins:link
1.  sfdx help hello:org

### Expected result

`$ sfdx hello:org [-n <string>] [-f] [-v <string>] [-u <string>] [--apiversion <string>] [--json] [--loglevel trace|debug|info|warn|error|fatal]`

### Actual result

`$ sfdx <%= command.id %> [-n <string>] [-f] [-v <string>] [-u <string>] [--apiversion <string>] [--json] [--loglevel trace|debug|info|warn|error|fatal]`

### Additional information

This is related to the changes in "@salesforce/command@1.3.0" (/forcedotcom/cli-packages#42)

**Comment by jayree** [comment]
@clairebianchi FYI

**Comment by amphro** [comment]
Thanks for the report @jayree - this should be fixed with `sfdx-cli` v7 scheduled for release on March 28th. I'll keep this open until confirmed.

**Comment by amphro** [comment]
This should be resolved now. Let me know if it is not.
